#!/bin/sh
# ====================================================================
#  generate_map_list.sh
#  SirenTorturers Edition (KFMapVoteST)
#
#  Regenerates Configs/KFMapVoteSTMapList.ini from whatever *.rom map
#  files currently sit in ../Maps (relative to this script's location -
#  the repo's Maps/ folder, a sibling of KFMapVoteST/). One
#  [<MapName> MapListEntry] PerObjectConfig section per map, matching
#  MapListEntry.uc's Config(KFMapVoteSTMapList) target.
#
#  Run this any time Maps/ changes, then rerun
#  GenerateMapPreviewsCommandlet - see MapListEntry.uc for why this
#  exists instead of relying on CacheManager.GetMapList().
# ====================================================================
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
MAPS_DIR="$SCRIPT_DIR/../Maps"
OUT_INI="$SCRIPT_DIR/Configs/KFMapVoteSTMapList.ini"

if [ ! -d "$MAPS_DIR" ]; then
	echo "generate_map_list.sh: Maps dir not found at $MAPS_DIR" >&2
	exit 1
fi

{
	echo "; ===================================================================="
	echo ";  KFMapVoteSTMapList.ini - GENERATED by generate_map_list.sh, do not"
	echo ";  hand-edit. Rerun the script instead after adding/removing maps."
	echo "; ===================================================================="
	for f in "$MAPS_DIR"/*.rom; do
		[ -e "$f" ] || continue
		name=$(basename "$f" .rom)
		echo "[$name MapListEntry]"
	done
} > "$OUT_INI"

count=$(find "$MAPS_DIR" -maxdepth 1 -iname "*.rom" -type f | wc -l | tr -d ' ')
echo "generate_map_list.sh: wrote $count map entries to $OUT_INI"
